
# goal conditioned bc
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 500 -wb --run_name ns_500
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 100 -wb --run_name ns_100
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  50 -wb --run_name ns_50
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  25 -wb --run_name ns_25
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  10 -wb --run_name ns_10
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   5 -wb --run_name ns_5
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   4 -wb --run_name ns_4
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   3 -wb --run_name ns_3
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   2 -wb --run_name ns_2


# supervised osil v1
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 500 -wb --run_name ns_500
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 100 -wb --run_name ns_100
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  50 -wb --run_name ns_50
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  25 -wb --run_name ns_25
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  10 -wb --run_name ns_10
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   5 -wb --run_name ns_5
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   4 -wb --run_name ns_4
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   3 -wb --run_name ns_3
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   2 -wb --run_name ns_2

# pseudo supervised osil (gcbc as decoder + pretrained encoder)
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --run_name gcbc+osil_emb_ns100
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -wb --run_name gcbc+osil_emb_ns5
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --run_name gcbc+osil_emb_ns4
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --run_name gcbc+osil_emb_ns3
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --run_name gcbc+osil_emb_ns2

# trying different k_neighbors for ns=5
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -kn 100 -wb --run_name gcbc+osil_emb_ns5_kn=100
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -kn 50 -wb --run_name gcbc+osil_emb_ns5_kn=50
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -kn 25 -wb --run_name gcbc+osil_emb_ns5_kn=25
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -kn 10 -wb --run_name gcbc+osil_emb_ns5_kn=10
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -kn 5 -wb --run_name gcbc+osil_emb_ns5_kn=5
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -kn 3 -wb --run_name gcbc+osil_emb_ns5_kn=3
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding.py -bs 128 --max_steps 10000  --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt   --model osil -kn 1 -wb --run_name gcbc+osil_emb_ns5_kn=1

#######################################################
# a new version of psuedo suprevised osil:
# instead of freezing the encoder, either fine-tune it 
# or start from scratch; just use the pretrained encoder
# for retrieving similar trajectories
#######################################################

# ns=5, self_emb (no kn), finetuned vs from scratch
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder --self_emb --run_name semi_osil_ns5_self_emb_ft
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --self_emb --run_name semi_osil_ns5_self_emb

# ns=100, self_emb (no kn), finetuned vs from scratch
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder --self_emb --run_name semi_osil_ns100_self_emb_ft
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --self_emb --run_name semi_osil_ns100_self_emb

# ns=5, knn retrieval (different kns), finetuned vs from scratch
CUDA_VISIBLE_DEVICES=1 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 1   --run_name semi_osil_ns5_ft_kn=1
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 3   --run_name semi_osil_ns5_ft_kn=3
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 5   --run_name semi_osil_ns5_ft_kn=5
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 10  --run_name semi_osil_ns5_ft_kn=10
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 25  --run_name semi_osil_ns5_ft_kn=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 50  --run_name semi_osil_ns5_ft_kn=50
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name semi_osil_ns5_ft_kn=100
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name semi_osil_ns5_ft_kn=200

CUDA_VISIBLE_DEVICES=1 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 1   --run_name semi_osil_ns5_kn=1
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 3   --run_name semi_osil_ns5_kn=3
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 5   --run_name semi_osil_ns5_kn=5
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 10  --run_name semi_osil_ns5_kn=10
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 25  --run_name semi_osil_ns5_kn=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 50  --run_name semi_osil_ns5_kn=50
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 100 --run_name semi_osil_ns5_kn=100
CUDA_VISIBLE_DEVICES=1 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/38tubxrp/checkpoints/cgl-step\=964-valid_loss\=0.1720-epoch\=964.ckpt  --model osil -wb --force_emb -kn 200 --run_name semi_osil_ns5_kn=200

# ns=100, knn retrieval (different kns), finetuned vs from scratch
CUDA_VISIBLE_DEVICES=1 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 1   --run_name semi_osil_ns100_ft_kn=1
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 3   --run_name semi_osil_ns100_ft_kn=3
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 5   --run_name semi_osil_ns100_ft_kn=5
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 10  --run_name semi_osil_ns100_ft_kn=10
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 25  --run_name semi_osil_ns100_ft_kn=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 50  --run_name semi_osil_ns100_ft_kn=50
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name semi_osil_ns100_ft_kn=100
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name semi_osil_ns100_ft_kn=200

CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 1   --run_name semi_osil_ns100_kn=1
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 3   --run_name semi_osil_ns100_kn=3
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 5   --run_name semi_osil_ns100_kn=5
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 10  --run_name semi_osil_ns100_kn=10
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 25  --run_name semi_osil_ns100_kn=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 50  --run_name semi_osil_ns100_kn=50
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 100 --run_name semi_osil_ns100_kn=100
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/3647wkjm/checkpoints/cgl-step\=6089-valid_loss\=0.0196-epoch\=608.ckpt  --model osil -wb --force_emb -kn 200 --run_name semi_osil_ns100_kn=200

# ns = 4, with finetuning, different kns
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name semi_osil_ns4_ft_kn=200
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name semi_osil_ns4_ft_kn=100
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name semi_osil_ns4_ft_kn=50
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name semi_osil_ns4_ft_kn=25
CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name semi_osil_ns4_ft_kn=10
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name semi_osil_ns4_ft_kn=5
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name semi_osil_ns4_ft_kn=3
CUDA_VISIBLE_DEVICES=1 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/7je3htz1/checkpoints/cgl-step\=865-valid_loss\=0.2645-epoch\=865.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name semi_osil_ns4_ft_kn=1


# ns = 3, with finetuning, different kns
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name semi_osil_ns3_ft_kn=200
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name semi_osil_ns3_ft_kn=100
CUDA_VISIBLE_DEVICES=1 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name semi_osil_ns3_ft_kn=50
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name semi_osil_ns3_ft_kn=25
CUDA_VISIBLE_DEVICES=1 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name semi_osil_ns3_ft_kn=10
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name semi_osil_ns3_ft_kn=5
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name semi_osil_ns3_ft_kn=3
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/2n02w2ux/checkpoints/cgl-step\=162-valid_loss\=0.3441-epoch\=162.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name semi_osil_ns3_ft_kn=1

# ns = 2, with finetuning, different kns
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name semi_osil_ns2_ft_kn=200
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name semi_osil_ns2_ft_kn=100
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name semi_osil_ns2_ft_kn=50
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name semi_osil_ns2_ft_kn=25
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name semi_osil_ns2_ft_kn=10
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name semi_osil_ns2_ft_kn=5
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name semi_osil_ns2_ft_kn=3
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/36m0n5z8/checkpoints/cgl-step\=280-valid_loss\=0.3464-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name semi_osil_ns2_ft_kn=1



# # supervised osil + mtm
# CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots 100 -wb --run_name tosil+mtm_maze2d_open_ns_100
# CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots  50 -wb --run_name tosil+mtm_maze2d_open_ns_50
# CUDA_VISIBLE_DEVICES=0 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots  25 -wb --run_name tosil+mtm_maze2d_open_ns_25
# CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots  10 -wb --run_name tosil+mtm_maze2d_open_ns_10
# CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots   5 -wb --run_name tosil+mtm_maze2d_open_ns_5
# CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots   4 -wb --run_name tosil+mtm_maze2d_open_ns_4
# CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots   3 -wb --run_name tosil+mtm_maze2d_open_ns_3
# CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_tosil_plus_mlm_joint.py -bs 128 --max_steps 10000 --dataset_path maze2d-open-v0_osil_short_trajs_v2/ --env_name maze2d-open-v0 --num_shots   2 -wb --run_name tosil+mtm_maze2d_open_ns_2