
# goal conditioned bc
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 500 -wb --run_name ns_500
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 100 -wb --run_name ns_100
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  50 -wb --run_name ns_50
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  25 -wb --run_name ns_25
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  10 -wb --run_name ns_10
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   5 -wb --run_name ns_5
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   4 -wb --run_name ns_4
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   3 -wb --run_name ns_3
CUDA_VISIBLE_DEVICES=0  python quick_test_scripts/train_gcbcv2.py -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   2 -wb --run_name ns_2


# supervised osil v1
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 500 -wb --run_name ns_500
CUDA_VISIBLE_DEVICES=2 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots 100 -wb --run_name ns_100
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  50 -wb --run_name ns_50
CUDA_VISIBLE_DEVICES=3 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  25 -wb --run_name ns_25
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots  10 -wb --run_name ns_10
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   5 -wb --run_name ns_5
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   4 -wb --run_name ns_4
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   3 -wb --run_name ns_3
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_tosilv1.py --max_padding 64 -bs 128 --max_steps 10000 --dataset_path reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --num_shots   2 -wb --run_name ns_2


# semi-supervised osil v3
# -------------------------
# ns 5, different kns
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name ns5_ft_kn=200
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name ns5_ft_kn=100
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name ns5_ft_kn=50
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name ns5_ft_kn=25
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name ns5_ft_kn=10
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name ns5_ft_kn=5
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name ns5_ft_kn=3
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000  --encoder_ckpt wandb_logs/osil/1qogs4xx/checkpoints/cgl-step\=1709-valid_loss\=0.3009-epoch\=854.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name ns5_ft_kn=1


# ns 2, different kns
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name ns2_ft_kn=200
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name ns2_ft_kn=100
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name ns2_ft_kn=50
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name ns2_ft_kn=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name ns2_ft_kn=10
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name ns2_ft_kn=5
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name ns2_ft_kn=3
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/14lmayhx/checkpoints/cgl-step\=1012-valid_loss\=0.3291-epoch\=1012.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name ns2_ft_kn=1


# ns 3, different kns
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name ns3_ft_kn=200
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name ns3_ft_kn=100
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name ns3_ft_kn=50
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name ns3_ft_kn=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name ns3_ft_kn=10
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name ns3_ft_kn=5
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name ns3_ft_kn=3
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/2zpxwdm0/checkpoints/cgl-step\=1899-valid_loss\=0.3026-epoch\=949.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name ns3_ft_kn=1

# ns 25, different kns
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name ns25_ft_kn=200
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name ns25_ft_kn=100
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name ns25_ft_kn=50
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name ns25_ft_kn=25
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name ns25_ft_kn=10
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name ns25_ft_kn=5
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name ns25_ft_kn=3
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/199bed0f/checkpoints/cgl-step\=2809-valid_loss\=0.2885-epoch\=280.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name ns25_ft_kn=1

# ns 100, different kns
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name ns100_ft_kn=200
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name ns100_ft_kn=100
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name ns100_ft_kn=50
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name ns100_ft_kn=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name ns100_ft_kn=10
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name ns100_ft_kn=5
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name ns100_ft_kn=3
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/30ne1tbg/checkpoints/cgl-step\=2659-valid_loss\=0.2854-epoch\=69.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name ns100_ft_kn=1


# What if we do multiple iterations of this student teacher training?
# ckpt round 2: wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt (kn=3,ns=2)
# ns 2, different kns
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 200 --run_name ns2_ft_iter2_kn1=3_kn2=200
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn 100 --run_name ns2_ft_iter2_kn1=3_kn2=100
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  50 --run_name ns2_ft_iter2_kn1=3_kn2=50
CUDA_VISIBLE_DEVICES=5 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  25 --run_name ns2_ft_iter2_kn1=3_kn2=25
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn  10 --run_name ns2_ft_iter2_kn1=3_kn2=10
CUDA_VISIBLE_DEVICES=7 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   5 --run_name ns2_ft_iter2_kn1=3_kn2=5
CUDA_VISIBLE_DEVICES=4 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   3 --run_name ns2_ft_iter2_kn1=3_kn2=3
CUDA_VISIBLE_DEVICES=6 python quick_test_scripts/train_gcbcv2_w_osil_embedding_v3.py --dataset_path ./reacher_7dof-v1_osil_dataset_v4/ --env_name reacher_7dof-v1 --max_padding 64 -bs 128 --max_steps 10000 --encoder_ckpt wandb_logs/osil/airssmyz/checkpoints/cgl-step\=1747-valid_loss\=0.2705-epoch\=45.ckpt   --model osil -wb --force_emb --finetune_encoder -kn   1 --run_name ns2_ft_iter2_kn1=3_kn2=1

