# @package agent
_target_: agent.ddpg.DDPGAgent
name: ddpg
obs_dim: ??? # to be specified later
action_dim: ??? # to be specified later
device: ${device}
lr: 1e-4
batch_size: 1024
nstep: 3
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 5000
critic_use_ln: true
critic_hidden_dims: [1024, 1024] #[512, 512, 256]
critic_spectral_norms: [true, true]
actor_use_ln: true
actor_hidden_dims: [1024, 1024] #[256, 256, 256]
actor_spectral_norms: [false, false]
stddev_schedule: 'linear(1.0,0.1,1000000)'
stddev_clip: 0.3